### PR TITLE
[WIP] Persistence for Dagon

### PR DESCRIPTION
**Pull request by bd339**
This is a pull request to track my progress towards supporting persistence in Dagon. This is initially based on version 0.65a so it can be tested against the Asylum teaser. If you wish to do the same, make a new clone of Dagon and perform a rollback to version 0.65a (in your new clone: `git reset --hard 416e1cb`). Eventually it will be rebased upon the latest version of Dagon. For testing against the Asylum teaser you can add the following code to Asylum.lua to be able to "quick-save" using the F5 key:
```
hotkey(F5, "saveGame()")

function saveGame()
    success,errorMsg = persist("dagon", { overwrite = true })
    if success then
        print("game saved!")
    else
        print(errorMsg)
    end
end
```

You will also need to create a `Saves` folder where the Dagon executable is.

## Initial design decisions
**SDL:** Dagon is already using the SDL so it seems like a good choice for file I/O, as it allows us to abstract away the endianness of the platform we are saving on.

**API:** The aim is to expose a simple API to the game's Lua scripts. The `persist` function is seen above in the `saveGame` function. It allows the programmer to name the save, and to allow or disallow overriding in case a save with the given name already exists. Default is false.
I would also like something like a `getSaves` function that will return a table of save names along with a "preview" text, possibly for displaying in the game's UI. Currently the "preview text" is automatically set to the current node's description upon saving.
Analogous to the `persist` function, a `unpersist` function that takes a save name as argument and maybe an optional argument in the form of a function to call after loading, should exist.

**File format:** This is still very much a work-in-progress, so this is just a rough outline of the planned format. In order of occurence in the save file:

1. Dagon version string (so we could support loading between engine versions, if any discrepancies arise with time)
2. Preview text as briefly discussed above
3. Number of global Lua variables persisted
4. Global Lua variables in a "KEY=VALUE" format
5. Internal engine data

Especially number 5 is very much "up in the air" at the moment.

### CODE REVIEW

**Comment by bd339** [comment]
@agustincordes I would really appreciate if you would take this for a test drive, to see if you spot any abnormalities in the produced save file. I'm not experienced enough with Dagon to know if some things are downright wrong, but it looks peculiar that it looks like some global variables in the Asylum teaser "embed" the global table itself... Contact me if you would like me to send you a save file in case you don't have the time to test for yourself at the moment.

Also notice how it only has saving as of yet, and I removed the code I said "actively avoided metatables" after our conversation about destruction of data. I figured it wouldn't make sense to go out of our way to avoid destroying metatables when we don't care about other unsupported data. However there is one thing in particular that I would like your opinion on: I think it would be straightforward to distinguish between a table that has elements but none of them are supported and an empty table. Therefore, we could easily avoid destroying tables that exclusively contain elements we don't support. Consider a table `t` of only functions.... I don't see much point in having `t={}` in the save file. In these cases we might as well omit saving that table. It saves disk space and it doesn't unnecessarily destroy data. Do you think this should be implemented?

**Comment by agustincordes** [comment]
@bd339 Fantastic work, woo! I'm having a bit of a hectic week here, so I'm afraid I won't be able to properly merge this for a few days. It's been a long time since I worked on the Dagon++ code and I see there's some conflicts that need to be resolved. That said, I can't wait to try this and "officially" revive the project :smile:

As for omitting certain tables: yes, I guess it wouldn't be too much extra work and as a result we'd have cleaner save files. As you say, it's also probably a safer process if we can avoid destroying/recreating certain stuff. Let me give you a more thorough answer when after I fully examine the pull request and do a few tests.

Again, thanks so much for doing this!

**Comment by bd339** [comment]
@agustincordes thanks for commenting on this.
About our efforts to have cleaner save files, arguments can certainly be made against the change as well. For one, it only makes sense to apply it to "non-nested tables". In the KEY=VALUE format, if the value is a table with a table inside, if that table inside is not saved, it would still be destroyed when loading. So it only works for tables that are a "direct members" of _G.
Another thing to consider is the case where a "direct member" of _G is referenced by another table. If we don't save that "direct member" but another variable references that table, we can't be sure the table exists when the save is loaded. If we don't apply the change we can at least make sure an empty table of that name exists!

**Comment by agustincordes** [comment]
@bd339 We may have an interesting opportunity to try this with an actual new game fully based on Dagon. It would be a far more complete test because the game is using a custom-made inventory and brings several tweaks to the Lua code.

How difficult would it be to merge your request with the current master? The project in question is using the latest 0.6.8a.

**Comment by bd339** [comment]
@agustincordes that would be very interesting - I'm all for it! It would provide a lot of useful insight to see how well the system fares against a possibly more complex use-case or at least a game that will actually benefit from persistence across sessions so we don't make a "useless" system by only testing against something that doesn't actually benefit from our changes.

As far as merging with master goes, my guess is that it won't be too difficult because it is mostly new code and whatever changes to existing code there are should be trivial to merge as long as there are at most insignificant changes to the Lua integration. Although I must admit I haven't looked in detail at the commits since 0.6.5a. I will give it a shot immediately so I suppose time will tell how wrong I am about the difficulty!

**Comment by agustincordes** [comment]
@bd339 Alright then, if the developer agrees, I will share a private demo of the game in question for full-blown testing! Here's hoping it's possible to merge with the latest commits. Truth to be told, I don't think there was anything major, just compatibility-breaking script changes and maintenance fixes. Let's keep in touch!

**Pull request merged**
